# Generated by Django 3.2.15 on 2022-12-07 16:33

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40)),
                ('bio', models.CharField(blank=True, max_length=400, null=True)),
                ('DOB', models.DateField(verbose_name='Date of Birth')),
                ('gender', models.CharField(choices=[(None, 'Choose your gender'), ('0', 'male'), ('1', 'female'), ('3', 'other')], max_length=6, verbose_name='gender')),
                ('discipline', models.CharField(blank=True, choices=[(None, 'Choose your primary discipline'), ('0', 'kayak'), ('1', 'canoe'), ('2', 'sup')], max_length=6, verbose_name='discipline')),
                ('classification', models.CharField(blank=True, choices=[('0', 'able-bodied'), ('1', 'para-canoe')], max_length=12, verbose_name='classification')),
                ('club', models.CharField(blank=True, max_length=50, verbose_name='club')),
                ('profile_pic', django_resized.forms.ResizedImageField(blank=True, crop=None, default=None, force_format=None, keep_meta=True, null=True, quality=100, scale=None, size=[50, 80], upload_to='athlete')),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40)),
                ('bio', models.CharField(blank=True, max_length=400, null=True)),
                ('profile_pic', django_resized.forms.ResizedImageField(blank=True, crop=None, default=None, force_format=None, keep_meta=True, null=True, quality=100, scale=None, size=[50, 80], upload_to='')),
                ('location', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40)),
                ('profile_pic', django_resized.forms.ResizedImageField(blank=True, crop=None, default=None, force_format=None, keep_meta=True, null=True, quality=100, scale=None, size=[50, 80], upload_to='team')),
                ('athletes', models.ManyToManyField(to='team.Athlete')),
                ('coaches', models.ManyToManyField(to='team.Coach')),
            ],
        ),
        migrations.AddField(
            model_name='athlete',
            name='coach',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='team.coach'),
        ),
    ]
